import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  video,
  content,
}: Readonly<{
  video: React.ReactNode;
  content: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div style={{ display: "flex", width: "100%", height: "100vh" }}>
          <div style={{ width: "70%", backgroundColor: "#333" }}>{video}</div>
          <div style={{ width: "30%", padding: "20px", overflowY: "auto" }}>
            {content}
          </div>
        </div>
      </body>
    </html>
  );
}
